version: "3.9"
services:
  openmrs:
    image: bahmni/openmrs:latest
    container_name: openmrs
    ports:
      - "8080:8080"
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      interval: 30s
      timeout: 10s
      retries: 5

  openelis:
    image: bahmni/openelis:latest
    container_name: openelis
    ports:
      - "8050:8050"
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050"]
      interval: 30s
      timeout: 10s
      retries: 5

  odoo:
    image: odoo:16
    container_name: odoo
    ports:
      - "8069:8069"
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069"]
      interval: 30s

         ysql:
    image: mysql:5.7
    container_name: mysql
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 10s
      retries: 5

  p ostgres:
    image: postgres:13
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 5

lumes:
    mysql_data:
    postgres_data:
