name: CI

on:
  push:
    branches:
      - main
      - staging
      - production
  pull_request:
    branches:
      - main
      - staging
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: echo "No dependencies to install yet"

      - name: Run tests
        run: echo "No tests defined yet"
